/// What-if parameter: demand price-elasticity used in the revenue simulation, -1.5 to
/// 0.0 in 0.1 steps. Disconnected calculated table; the report binds a slider to it.
/// Category guides: ZYN ~= -0.7, VEEV ~= -0.9 (global slider default -0.8).
table Elasticity
	lineageTag: e8b2c3d4-0001-4a5b-9c7d-c00000000001

	/// Currently selected elasticity (defaults to -0.8).
	measure 'Elasticity Value' = SELECTEDVALUE(Elasticity[Elasticity], -0.8)
		formatString: 0.0
		lineageTag: e8b2c3d4-0101-4a5b-9c7d-c00000000101

	column Elasticity
		dataType: double
		formatString: 0.0
		lineageTag: e8b2c3d4-0011-4a5b-9c7d-c00000000011
		summarizeBy: none
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition Elasticity = calculated
		mode: import
		source = GENERATESERIES(-1.5, 0.0001, 0.1)

