/// What-if parameter: price change applied in the revenue simulation, -20% to +30%
/// in 1% steps. A disconnected calculated table; the report binds a slider to it.
table 'Price Change %'
	lineageTag: e7b2c3d4-0001-4a5b-9c7d-b00000000001

	/// Currently selected price change % (defaults to 0% = no change).
	measure 'Price Change % Value' = SELECTEDVALUE('Price Change %'[Price Change %], 0)
		formatString: 0%;-0%;0%
		lineageTag: e7b2c3d4-0101-4a5b-9c7d-b00000000101

	column 'Price Change %'
		dataType: double
		formatString: 0%;-0%;0%
		lineageTag: e7b2c3d4-0011-4a5b-9c7d-b00000000011
		summarizeBy: none
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition 'Price Change %' = calculated
		mode: import
		source = GENERATESERIES(-0.2, 0.3001, 0.01)

